version: '3'
services:
  frontend:
    image: frontend
    build: 
       context: .
       dockerfile: Frontend/Dockerfile
    ports:
      - "5000:5000"
  dbservice:
    image: dbservice
    build:
      context: .
      dockerfile: DbService/Dockerfile
    ports:
      - "5001:5001"
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  kibana:
    image: elastic/kibana:7.1.1
    ports:
      - 5601:5601
  apmserver:
    image: elastic/apm-server:7.1.1
    ports:
      - 8200:8200
# Names our volume
volumes:
  my-db: